/*
 * UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE - UFRN
 * DEPARTAMENTO DE INFORMÁTICA E MATEMÁTICA APLICADA - DIMAP
 * Programa de Pós-Graduação em Sistemas e Computação - PPGSC
 */
package br.ufrn.spl.ev.engines.conflicts.statistics;

/**
 * @author gleydson
 * @author jadson - jadson@info.ufrn.br
 *
 */
public interface CollectCompleteStatisticConstants {
	

	public static final String EVOLUTIONS_TOTAL_TASK = "EVOLUTIONS_TOTAL_TASK";
	public static final String EVOLUTIONS_TOTAL_TASK_NO_CONFLICT = "EVOLUTIONS_TOTAL_TASK_NO_CONFLICT";
	public static final String EVOLUTIONS_TOTAL_ATOMIC = "EVOLUTIONS_TOTAL_ATOMIC";
	public static final String EVOLUTIONS_TOTAL_TASK_VARIABIITY_PATTERN = "EVOLUTIONS_TOTAL_TASK_VARIABIITY_PATTERN";
	public static final String EVOLUTIONS_TOTAL_TASK_VARIABIITY_CONDEXEC = "EVOLUTIONS_TOTAL_TASK_VARIABIITY_CONDEXEC";
	public static final String EVOLUTIONS_TOTAL_TASK_VARIABIITY_CONFLICT = "EVOLUTIONS_TOTAL_TASK_VARIABIITY_CONFLICT";
	public static final String EVOLUTIONS_TOTAL_TASK_CORE = "EVOLUTIONS_TOTAL_TASK_CORE";
	
	public static final String EVOLUTIONS_TASK_NEW_FUNCIONALITY = "EVOLUTIONS_TASK_NEW_FUNCIONALITY";
	public static final String EVOLUTIONS_TASK_BUG_FIX = "EVOLUTIONS_TASK_BUG_FIX";
	public static final String EVOLUTIONS_TASK_NEW_USE_CASE = "EVOLUTIONS_TASK_NEW_USE_CASE";

	public static final String EVOLUTIONS_ATOMIC_CLASS_MODIFIED = "EVOLUTIONS_ATOMIC_CLASS_MODIFIED";
	public static final String EVOLUTIONS_ATOMIC_CLASS_ADDED = "EVOLUTIONS_ATOMIC_CLASS_ADDED";
	public static final String EVOLUTIONS_ATOMIC_UPDATED_CLASS = "EVOLUTIONS_ATOMIC_UPDATED_CLASS";
	public static final String EVOLUTIONS_ATOMIC_CLASS_REMOVED = "EVOLUTIONS_ATOMIC_CLASS_REMOVED";

	public static final String EVOLUTIONS_ATOMIC_FIELD_ADDED = "EVOLUTIONS_ATOMIC_FIELD_ADDED";
	public static final String EVOLUTIONS_ATOMIC_FIELD_UPDATED = "EVOLUTIONS_ATOMIC_FIELD_UPDATED";
	public static final String EVOLUTIONS_ATOMIC_FIELD_REMOVED = "EVOLUTIONS_ATOMIC_FIELD_REMOVED";

	public static final String EVOLUTIONS_ATOMIC_METHOD_ADDED = "EVOLUTIONS_ATOMIC_METHOD_ADDED";
	public static final String EVOLUTIONS_ATOMIC_METHOD_UPDATED = "EVOLUTIONS_ATOMIC_METHOD_UPDATED";
	public static final String EVOLUTIONS_ATOMIC_METHOD_REMOVED = "EVOLUTIONS_ATOMIC_METHOD_REMOVED";

	public static final String DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK = "DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK";
	public static final String DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY = "DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY";
	public static final String DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC = "DIRECT_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC";

	public static final String DIRECT_CONFLICTING_TASK_NEW_FUNCIONALITY = "DIRECT_CONFLICTING_TASK_NEW_FUNCIONALITY";
	public static final String DIRECT_CONFLICTING_TASK_BUG_FIX = "DIRECT_CONFLICTING_TASK_BUG_FIX";
	public static final String DIRECT_CONFLICTING_TASK_NEW_USE_CASE = "DIRECT_CONFLICTING_TASK_NEW_USE_CASE";

	public static final String DIRECT_CONFLICTING_ATOMIC_CLASS_ADDED = "DIRECT_CONFLICTING_ATOMIC_CLASS_ADDED";
	public static final String DIRECT_CONFLICTING_ATOMIC_CLASS_UPDATED = "DIRECT_CONFLICTING_ATOMIC_CLASS_UPDATED";
	public static final String DIRECT_CONFLICTING_ATOMIC_CLASS_REMOVED = "DIRECT_CONFLICTING_ATOMIC_CLASS_REMOVED";

	public static final String DIRECT_CONFLICTING_ATOMIC_FIELD_ADDED = "DIRECT_CONFLICTING_ATOMIC_FIELD_ADDED";
	public static final String DIRECT_CONFLICTING_ATOMIC_FIELD_UPDATED = "DIRECT_CONFLICTING_ATOMIC_FIELD_UPDATED";
	public static final String DIRECT_CONFLICTING_ATOMIC_FIELD_REMOVED = "DIRECT_CONFLICTING_ATOMIC_FIELD_REMOVED";

	public static final String DIRECT_CONFLICTING_ATOMIC_METHOD_ADDED = "DIRECT_CONFLICTING_ATOMIC_METHOD_ADDED";
	public static final String DIRECT_CONFLICTING_ATOMIC_METHOD_UPDATED = "DIRECT_CONFLICTING_ATOMIC_METHOD_UPDATED";
	public static final String DIRECT_CONFLICTING_ATOMIC_METHOD_REMOVED = "DIRECT_CONFLICTING_ATOMIC_METHOD_REMOVED";

	public static final String INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK = "INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK";
	public static final String INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY = "INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY";
	public static final String INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC = "INDIRECT_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC";
	
	public static final String INDIRECT_CONFLICTING_TASK_NEW_FUNCIONALITY = "INDIRECT_CONFLICTING_TASK_NEW_FUNCIONALITY";
	public static final String INDIRECT_CONFLICTING_TASK_BUG_FIX = "INDIRECT_CONFLICTING_TASK_BUG_FIX";
	public static final String INDIRECT_CONFLICTING_TASK_NEW_USE_CASE = "INDIRECT_CONFLICTING_TASK_NEW_USE_CASE";

	public static final String INDIRECT_CONFLICTING_ATOMIC_CLASS_ADDED = "INDIRECT_CONFLICTING_ATOMIC_CLASS_ADDED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_CLASS_UPDATED = "INDIRECT_CONFLICTING_ATOMIC_CLASS_UPDATED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_CLASS_REMOVED = "INDIRECT_CONFLICTING_ATOMIC_CLASS_REMOVED";

	public static final String INDIRECT_CONFLICTING_ATOMIC_FIELD_ADDED = "INDIRECT_CONFLICTING_ATOMIC_FIELD_ADDED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_FIELD_UPDATED = "INDIRECT_CONFLICTING_ATOMIC_FIELD_UPDATED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_FIELD_REMOVED = "INDIRECT_CONFLICTING_ATOMIC_FIELD_REMOVED";

	public static final String INDIRECT_CONFLICTING_ATOMIC_METHOD_ADDED = "INDIRECT_CONFLICTING_ATOMIC_METHOD_ADDED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_METHOD_UPDATED = "INDIRECT_CONFLICTING_ATOMIC_METHOD_UPDATED";
	public static final String INDIRECT_CONFLICTING_ATOMIC_METHOD_REMOVED = "INDIRECT_CONFLICTING_ATOMIC_METHOD_REMOVED";

	public static final String TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_TASK = "TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_TASK";
	public static final String TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY = "TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_TASK_VARIABILITY";
	public static final String TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC = "TEXTUAL_CONFLICTING_TOTAL_EVOLUTIONS_ATOMIC";
	
	public static final String DIRECT_CONFLICTING_LAYER_BUSINESS = "DIRECT_CONFLICTING_LAYER_BUSINESS";
	public static final String DIRECT_CONFLICTING_LAYER_DATA_ACCESS = "DIRECT_CONFLICTING_LAYER_DATA_ACCESS";
	public static final String DIRECT_CONFLICTING_LAYER_WEB = "DIRECT_CONFLICTING_LAYER_WEB";
	public static final String DIRECT_CONFLICTING_LAYER_ENTITY = "DIRECT_CONFLICTING_LAYER_ENTITY";
	public static final String DIRECT_CONFLICTING_LAYER_OTHERS = "DIRECT_CONFLICTING_LAYER_OTHERS";

	public static final String INDIRECT_CONFLICTING_LAYER_BUSINESS = "INDIRECT_CONFLICTING_LAYER_BUSINESS";
	public static final String INDIRECT_CONFLICTING_LAYER_DATA_ACCESS = "INDIRECT_CONFLICTING_LAYER_DATA_ACCESS";
	public static final String INDIRECT_CONFLICTING_LAYER_WEB = "INDIRECT_CONFLICTING_LAYER_WEB";
	public static final String INDIRECT_CONFLICTING_LAYER_ENTITY = "INDIRECT_CONFLICTING_LAYER_ENTITY";
	public static final String INDIRECT_CONFLICTING_LAYER_OTHERS = "INDIRECT_CONFLICTING_LAYER_OTHERS";

	public static final String TEXTUAL_CONFLICTING_LAYER_BUSINESS = "TEXTUAL_CONFLICTING_LAYER_BUSINESS";
	public static final String TEXTUAL_CONFLICTING_LAYER_DATA_ACCESS = "TEXTUAL_CONFLICTING_LAYER_DATA_ACCESS";
	public static final String TEXTUAL_CONFLICTING_LAYER_WEB = "TEXTUAL_CONFLICTING_LAYER_WEB";
	public static final String TEXTUAL_CONFLICTING_LAYER_ENTITY = "TEXTUAL_CONFLICTING_LAYER_ENTITY";
	public static final String TEXTUAL_CONFLICTING_LAYER_OTHERS = "TEXTUAL_CONFLICTING_LAYER_OTHERS";

	public static final String TEXTUAL_CONFLICTING_TASK_NEW_FUNCIONALITY = "TEXTUAL_CONFLICTING_TASK_NEW_FUNCIONALITY";
	public static final String TEXTUAL_CONFLICTING_TASK_BUG_FIX = "TEXTUAL_CONFLICTING_TASK_BUG_FIX";
	public static final String TEXTUAL_CONFLICTING_TASK_NEW_USE_CASE = "TEXTUAL_CONFLICTING_TASK_NEW_USE_CASE";
	
	public static final String TEXTUAL_CONFLICTING_ATOMIC_CLASS_UPDATED = "TEXTUAL_CONFLICTING_ATOMIC_CLASS_UPDATED";
	
	//public static final String TOTAL_EVOLUTIONS_VARIABILITY = "TOTAL_EVOLUTIONS_VARIABILITY";
	public static final String TOTAL_EVOLUTIONS_VARIABILITY_PATTERN = "TOTAL_EVOLUTIONS_VARIABILITY_PATTERN";
	public static final String TOTAL_EVOLUTIONS_VARIABILITY_CONDITIONAL_EXEC = "TOTAL_EVOLUTIONS_VARIABILITY_CONDITIONAL_EXEC";

	public static final String DIRECT_CONFLICTING_VARIABILITY_PATTERN = "DIRECT_CONFLICTS_VARIABILITY_PATTERN";
	public static final String DIRECT_CONFLICTING_VARIABILITY_CONDITIONAL_EXEC = "DIRECT_CONFLICTS_VARIABILITY_CONDITIONAL_EXEC";
	
	public static final String INDIRECT_CONFLICTING_VARIABILITY_PATTERN = "INDIRECT_CONFLICTS_VARIABILITY_PATTERN";
	public static final String INDIRECT_CONFLICTING_VARIABILITY_CONDITIONAL_EXEC = "INDIRECT_CONFLICTS_VARIABILITY_CONDITIONAL_EXEC";
	
	public static final String TEXTUAL_CONFLICTING_VARIABILITY_PATTERN = "TEXTUAL_CONFLICTS_VARIABILITY_PATTERN";
	public static final String TEXTUAL_CONFLICTING_VARIABILITY_CONDITIONAL_EXEC= "TEXTUAL_CONFLICTS_VARIABILITY_CONDITIONAL_EXEC";
	
	
	public static final String TASK_CONFLICT_ONLY_DIRECT = "TASK_CONFLICT_ONLY_DIRECT";
	public static final String TASK_CONFLICT_ONLY_INDIRECT = "TASK_CONFLICT_ONLY_INDIRECT";
	public static final String TASK_CONFLICT_ONLY_TEXTUAL = "TASK_CONFLICT_ONLY_TEXTUAL";
	public static final String TASK_CONFLICT_DIRECT_AND_TEXTUAL = "TASK_CONFLICT_DIRECT_AND_TEXTUAL";
	public static final String TASK_CONFLICT_DIRECT_AND_INDIRECT = "TASK_CONFLICT_DIRECT_AND_INDIRECT";
	public static final String TASK_CONFLICT_INDIRECT_AND_TEXTUAL = "TASK_CONFLICT_INDIRECT_AND_TEXTUAL";
	public static final String TASK_CONFLICT_INDIRECT_AND_TEXTUAL_DIRECT = "TASK_CONFLICT_INDIRECT_AND_TEXTUAL_DIRECT";
	

}
